#!/Users/makkena/Desktop/INTELLIGENT-MEDICAL-ASSISTANT-CHATBOT-USING-THE-LLM-main/.venv/bin/python3
import sys
from cookiecutter.__main__ import main
if __name__ == '__main__':
    sys.argv[0] = sys.argv[0].removesuffix('.exe')
    sys.exit(main())
