AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: MediBot - AI Medical Chatbot with Step-by-Step Visual Instructions

Globals:
  Function:
    Timeout: 300  # 5 minutes for step-by-step image generation
    MemorySize: 1024

Parameters:
  GoogleApiKey:
    Type: String
    NoEcho: true
    Description: Google AI API Key for Gemini models
  
  BedrockBearerToken:
    Type: String
    NoEcho: true
    Description: AWS Bedrock Bearer Token for Titan image generation
  
  GeminiLlmModel:
    Type: String
    Default: gemini-2.0-flash
    Description: Gemini Model ID for LLM (text generation)
  
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - staging
    Description: Deployment environment

Resources:
  # Lambda Function for FastAPI Backend
  MediBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub medibot-api-${Environment}
      CodeUri: ../backend/
      Handler: lambda_handler.handler
      Runtime: python3.11
      Timeout: 90  # 90 seconds for image generation
      MemorySize: 1024  # 1GB RAM
      Architectures:
        - arm64  # Cost-effective ARM architecture
      Environment:
        Variables:
          GOOGLE_API_KEY: !Ref GoogleApiKey
          AWS_BEARER_TOKEN_BEDROCK: !Ref BedrockBearerToken
          GEMINI_LLM_MODEL: !Ref GeminiLlmModel
          BEDROCK_REGION: !Ref AWS::Region
          ENVIRONMENT: !Ref Environment
          IMAGES_BUCKET: !Ref ImagesBucket
          # Phase 2: Auth & Storage
          COGNITO_USER_POOL_ID: !Ref UserPool
          COGNITO_CLIENT_ID: !Ref UserPoolClient
          CHAT_TABLE: !Ref ChatHistoryTable
          REPORTS_BUCKET: !Ref ReportsBucket
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource: "*"
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
              Resource: !Sub ${ImagesBucket.Arn}/*
            # Phase 2: DynamoDB permissions
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:Query
                - dynamodb:DeleteItem
                - dynamodb:UpdateItem
              Resource:
                - !GetAtt ChatHistoryTable.Arn
                - !Sub ${ChatHistoryTable.Arn}/index/*
            # Phase 2: Reports bucket permissions
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
                - s3:DeleteObject
              Resource: !Sub ${ReportsBucket.Arn}/*
      Events:
        ApiRoot:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
            ApiId: !Ref MediBotApi
        ApiProxy:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
            ApiId: !Ref MediBotApi

  # HTTP API Gateway
  MediBotApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref Environment
      CorsConfiguration:
        AllowOrigins:
          - "https://d17eixu2k5iihu.cloudfront.net"
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
          - X-Requested-With
        MaxAge: 86400

  # S3 Bucket for Generated Images (public read access)
  ImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub medibot-images-${AWS::AccountId}-${AWS::Region}-${Environment}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET]
            AllowedOrigins: ['*']
            MaxAge: 3600
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldImages
            Status: Enabled
            ExpirationInDays: 1  # Auto-delete images after 1 day

  # Public read policy for images bucket
  ImagesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ImagesBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub ${ImagesBucket.Arn}/*

  # ============================================
  # Phase 2: User Authentication & Data Storage
  # ============================================

  # Cognito User Pool for authentication
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub medibot-users-${Environment}
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireUppercase: true
          RequireNumbers: true
          RequireSymbols: false
      Schema:
        - Name: email
          Required: true
          Mutable: true
        - Name: name
          Required: false
          Mutable: true

  # Cognito App Client
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub medibot-web-${Environment}
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      PreventUserExistenceErrors: ENABLED
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - https://d17eixu2k5iihu.cloudfront.net
        - http://localhost:3000
      LogoutURLs:
        - https://d17eixu2k5iihu.cloudfront.net
        - http://localhost:3000
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true

  # DynamoDB Table for Chat History
  ChatHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub medibot-chats-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: chat_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: chat_id
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: timestamp-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  # S3 Bucket for Medical Reports (private, encrypted)
  ReportsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub medibot-reports-${AWS::AccountId}-${AWS::Region}-${Environment}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, PUT, POST]
            AllowedOrigins:
              - https://d17eixu2k5iihu.cloudfront.net
              - http://localhost:3000
            MaxAge: 3600
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldReports
            Status: Enabled
            ExpirationInDays: 30  # Auto-delete reports after 30 days

  # S3 Bucket for Frontend Static Files
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub medibot-frontend-${AWS::AccountId}-${AWS::Region}-${Environment}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html

  # CloudFront Origin Access Identity
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub OAI for MediBot Frontend ${Environment}

  # S3 Bucket Policy for CloudFront
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOAI.S3CanonicalUserId
            Action: s3:GetObject
            Resource: !Sub ${FrontendBucket.Arn}/*

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOAI}
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6  # CachingOptimized
          Compress: true
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        PriceClass: PriceClass_100
        HttpVersion: http2

Outputs:
  ApiUrl:
    Description: API Gateway URL for the MediBot backend
    Value: !Sub "https://${MediBotApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
    Export:
      Name: !Sub ${AWS::StackName}-ApiUrl

  FrontendBucketName:
    Description: S3 bucket for frontend static files
    Value: !Ref FrontendBucket
    Export:
      Name: !Sub ${AWS::StackName}-FrontendBucket

  CloudFrontUrl:
    Description: CloudFront distribution URL for the frontend
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"
    Export:
      Name: !Sub ${AWS::StackName}-CloudFrontUrl

  CloudFrontDistributionId:
    Description: CloudFront distribution ID (for cache invalidation)
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub ${AWS::StackName}-CloudFrontDistributionId

  # Phase 2 Outputs
  CognitoUserPoolId:
    Description: Cognito User Pool ID for authentication
    Value: !Ref UserPool
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolId

  CognitoClientId:
    Description: Cognito App Client ID for frontend
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolClientId

  CognitoRegion:
    Description: AWS Region for Cognito
    Value: !Ref AWS::Region

  ChatHistoryTableName:
    Description: DynamoDB table for chat history
    Value: !Ref ChatHistoryTable
    Export:
      Name: !Sub ${AWS::StackName}-ChatTable

  ReportsBucketName:
    Description: S3 bucket for medical reports
    Value: !Ref ReportsBucket
    Export:
      Name: !Sub ${AWS::StackName}-ReportsBucket
