AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: MediBot - AI Medical Chatbot with Step-by-Step Visual Instructions

Globals:
  Function:
    Timeout: 300  # 5 minutes for step-by-step image generation
    MemorySize: 1024

Parameters:
  BedrockBearerToken:
    Type: String
    NoEcho: true
    Description: AWS Bedrock Bearer Token for API authentication
  
  BedrockLlmModel:
    Type: String
    Default: mistral.mistral-small-2402-v1:0
    Description: Bedrock Model ID for LLM (switched to Small for speed < 30s latency)
  
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - staging
    Description: Deployment environment

Resources:
  # Lambda Function for FastAPI Backend
  MediBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub medibot-api-${Environment}
      CodeUri: ../backend/
      Handler: lambda_handler.handler
      Runtime: python3.11
      Architectures:
        - arm64  # Cost-effective ARM architecture
      Environment:
        Variables:
          AWS_BEARER_TOKEN_BEDROCK: !Ref BedrockBearerToken
          BEDROCK_REGION: !Ref AWS::Region
          BEDROCK_LLM_MODEL: mistral.mistral-large-3-675b-instruct
          ENVIRONMENT: !Ref Environment
          IMAGES_BUCKET: !Ref ImagesBucket
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource: "*"
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
              Resource: !Sub ${ImagesBucket.Arn}/*
      Events:
        ApiRoot:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
            ApiId: !Ref MediBotApi
        ApiProxy:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
            ApiId: !Ref MediBotApi

  # HTTP API Gateway
  MediBotApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref Environment
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
          - X-Requested-With
        MaxAge: 86400

  # S3 Bucket for Generated Images (public read access)
  ImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub medibot-images-${AWS::AccountId}-${AWS::Region}-${Environment}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET]
            AllowedOrigins: ['*']
            MaxAge: 3600
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldImages
            Status: Enabled
            ExpirationInDays: 1  # Auto-delete images after 1 day

  # Public read policy for images bucket
  ImagesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ImagesBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub ${ImagesBucket.Arn}/*

  # S3 Bucket for Frontend Static Files
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub medibot-frontend-${AWS::AccountId}-${AWS::Region}-${Environment}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html

  # CloudFront Origin Access Identity
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub OAI for MediBot Frontend ${Environment}

  # S3 Bucket Policy for CloudFront
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOAI.S3CanonicalUserId
            Action: s3:GetObject
            Resource: !Sub ${FrontendBucket.Arn}/*

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOAI}
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6  # CachingOptimized
          Compress: true
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        PriceClass: PriceClass_100
        HttpVersion: http2

Outputs:
  ApiUrl:
    Description: API Gateway URL for the MediBot backend
    Value: !Sub "https://${MediBotApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
    Export:
      Name: !Sub ${AWS::StackName}-ApiUrl

  FrontendBucketName:
    Description: S3 bucket for frontend static files
    Value: !Ref FrontendBucket
    Export:
      Name: !Sub ${AWS::StackName}-FrontendBucket

  CloudFrontUrl:
    Description: CloudFront distribution URL for the frontend
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"
    Export:
      Name: !Sub ${AWS::StackName}-CloudFrontUrl

  CloudFrontDistributionId:
    Description: CloudFront distribution ID (for cache invalidation)
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub ${AWS::StackName}-CloudFrontDistributionId
